jupyter_elfinder/elfinder.py

The url was not join properly, this is a fix for it.

Fix preview url bug

---

LICENSE
jupyter_elfinder/__init__.py
jupyter_elfinder/elfinder.py
setup.py

- Found one potential bug from the spell check.
This PR depends on #4

Fix spelling

---

Makefile

- Add some convenient commands to the makefile and help.
This PR depends on #5.

Extend makefile

---

.github/workflow/test.yml
tox.ini

- Add github actions CI.
This PR depends on #7.

Add GitHub actions CI

---

.coveragerc
pylintrc
setup.cfg

Add test and linting settings

---

setup.py

- Clean up setup.py lint warnings.

Clean setup

---

jupyter_elfinder/elfinder.py

- I think we need some unit tests. :smile:

Fix decoding string

---

jupyter_elfinder/static/js/elfinder.full.js
jupyter_elfinder/static/main.js
jupyter_elfinder/templates/elfinder/elfinder.html

This add file_base_url option for imjoy plugins.

Add file_base_url for imjoy plugins

---

setup.cfg

- This isort config is compatible with black.

Add isort config

---

jupyter_elfinder/elfinder.py
jupyter_elfinder/util.py
jupyter_elfinder/views.py
tests/__init__.py
tests/conftest.py
tests/test_elfinder.py
tests/test_views.py

- To make it easier to test the backend with pyramids testing request framework we replace the MultiDict api use with our own util functions.

Add more tests

---

jupyter_elfinder/elfinder.py

- This just moves methods around and adds a comment. No functional changes.

Group commands and helpers

---

.github/workflows/test.yml

- Do not limit target branch for CI test in PRs.

Run CI tests on all PRs

---

requirements.txt
setup.py

- For tests we want to pin all requirements.
- For user installs we want more relaxed pinning.

Pin and split requirements source

---

.github/release-drafter.yml
.github/workflows/draft-release.yml

-  This will create and update a draft release every time a pull request is merged.
- When we're ready to release we edit the draft release and publish it.

Add release drafter

---

.github/workflows/draft-release.yml

- Add workflow_dispatch trigger to the draft-release workflow.

Allow manually triggering draft release action

---

.github/workflows/draft-release.yml
.github/workflows/release.yml
requirements_pypi.txt

- Release to PyPI and tag a GitHub release automatically when detecting a version bump.

Add release action

---

.github/release-drafter.yml
.github/workflows/draft-release.yml
.github/workflows/release.yml

- Use the autolabeler feature of release-drafter.

Label PRs automatically

---

.github/labels.yml
.github/workflows/labeler.yml

- Make sure labels used by CI are correct.

Add labeler to manage labels

---

imjoy_elfinder/util.py

This PR fixes the `get_all` function and made the multi-parts upload work.
Fixes https://github.com/imjoy-team/imjoy-elfinder/issues/145

Fix multi-upload

---

.github/workflows/test.yml
README.md
setup.py
tox.ini

Remove support for Python 3.6
